
package aruhaz;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AruhazJFrame extends javax.swing.JFrame {


    public AruhazJFrame() {
        initComponents();
    }
    Aruhaz aruhaz;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableButorok = new javax.swing.JTable();
        btListazas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lAruhazNev = new javax.swing.JLabel();
        lAruhazFileNev = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btFHozzaadas = new javax.swing.JButton();
        tfFNev = new javax.swing.JTextField();
        tfFAr = new javax.swing.JTextField();
        tfFSuly = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfKNev = new javax.swing.JTextField();
        tfKAr = new javax.swing.JTextField();
        tfKAnyag = new javax.swing.JTextField();
        btKHozzaadas = new javax.swing.JButton();
        btFelujitas = new javax.swing.JButton();
        btMasolas = new javax.swing.JButton();
        btModositas = new javax.swing.JButton();
        btRendezes = new javax.swing.JButton();
        btExportalas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableButorok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sorszám", "Bútor név", "Ár", "Súly", "Anyag"
            }
        ));
        jTableButorok.setGridColor(java.awt.SystemColor.activeCaption);
        jTableButorok.setSelectionBackground(java.awt.SystemColor.activeCaption);
        jScrollPane1.setViewportView(jTableButorok);

        btListazas.setBackground(java.awt.SystemColor.activeCaption);
        btListazas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btListazas.setText("Listázás");
        btListazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListazasActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Áruház", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), javax.swing.UIManager.getDefaults().getColor("Actions.Blue"))); // NOI18N
        jPanel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jLabel2.setText("Név:");

        jLabel3.setText("File név:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAruhazNev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lAruhazFileNev, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lAruhazFileNev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lAruhazNev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.control);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel4.setText("Bútor hozzáadása");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Fa bútor");

        jLabel6.setText("Név");

        jLabel7.setText("Ár");

        jLabel8.setText("Súly");

        btFHozzaadas.setBackground(java.awt.SystemColor.activeCaption);
        btFHozzaadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFHozzaadas.setText("Hozzáadás");
        btFHozzaadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFHozzaadasActionPerformed(evt);
            }
        });

        jLabel9.setText("Név");

        jLabel10.setText("Ár");

        jLabel11.setText("Anyag");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Kárpitozott bútor");

        btKHozzaadas.setBackground(java.awt.SystemColor.activeCaption);
        btKHozzaadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btKHozzaadas.setText("Hozzáadás");
        btKHozzaadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKHozzaadasActionPerformed(evt);
            }
        });

        btFelujitas.setBackground(java.awt.SystemColor.activeCaption);
        btFelujitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFelujitas.setText("Felújítás");
        btFelujitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFelujitasActionPerformed(evt);
            }
        });

        btMasolas.setBackground(java.awt.SystemColor.activeCaption);
        btMasolas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btMasolas.setText("Másolás");
        btMasolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMasolasActionPerformed(evt);
            }
        });

        btModositas.setBackground(java.awt.SystemColor.activeCaption);
        btModositas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btModositas.setText("Módosítás");
        btModositas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModositasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFHozzaadas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFNev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFAr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFSuly, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tfKNev, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(btFelujitas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfKAr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfKAnyag, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btKHozzaadas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btModositas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btMasolas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfFNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfKNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFelujitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfFAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfKAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMasolas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfFSuly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfKAnyag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModositas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFHozzaadas)
                    .addComponent(btKHozzaadas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btRendezes.setBackground(java.awt.SystemColor.activeCaption);
        btRendezes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btRendezes.setText("Rendezés");
        btRendezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRendezesActionPerformed(evt);
            }
        });

        btExportalas.setBackground(java.awt.SystemColor.activeCaption);
        btExportalas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExportalas.setText("Exportálás");
        btExportalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportalasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btListazas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btRendezes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btExportalas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListazas)
                    .addComponent(btRendezes)
                    .addComponent(btExportalas))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*Áruház létrehozása
    Nevének és raktárkészletet tároló file nevének megadása*/
    public void aruhazLetrehozasa(String nev, String fileNev){
        lAruhazNev.setText(nev);
        lAruhazFileNev.setText(fileNev);
        //Hibás file esetén az áruház létrehozása nem lehetséges
        try{
            aruhaz=new Aruhaz(nev,fileNev);
            JOptionPane.showMessageDialog(this,"Áruház sikeresen létrehozva!");
        }
        catch(ClassNotFoundException | IOException c){
            JOptionPane.showMessageDialog(this,"Áruház létrehozása nem lehetséges!","Error",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }  
    }

    private void tablazatbaIr(ArrayList<Butor> butorok){
        //
        DefaultTableModel tblModel = (DefaultTableModel)jTableButorok.getModel();
        
        tblModel.setRowCount(0);
        for(int i=0;i<butorok.size();i++){
            if(butorok.get(i) instanceof FaButor f){
                String data[] = {String.valueOf(i+1),f.getNev(),String.valueOf(f.getErtek()),String.valueOf(f.getSuly()),"N/A"};

                
                tblModel.addRow(data);
            }
            else if(butorok.get(i) instanceof KarpitozottButor f){
                String data[] = {String.valueOf(i+1),f.getNev(),String.valueOf(f.getErtek()),"N/A",String.valueOf(f.getAnyag())};

                tblModel.addRow(data);
            }
        }    
    }
  
    //Bútorok listázása a táblázatba
    private void btListazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListazasActionPerformed
        tablazatbaIr(aruhaz.getButorok());
    }//GEN-LAST:event_btListazasActionPerformed
    
    //Bútorok rendezése érték szerint
    private void btRendezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRendezesActionPerformed
        tablazatbaIr(aruhaz.rendezes());
    }//GEN-LAST:event_btRendezesActionPerformed

    //Fa bútor hozzáadása
    private void btFHozzaadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFHozzaadasActionPerformed
        //Kötelező adatok megadásának ellenőrzése
        if(tfFNev.getText().equals("")||tfFSuly.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Hiányzó adat!","Error",JOptionPane.ERROR_MESSAGE);        
        }
        //Ha a bútor értéke nem került megadásra, akkor a default értéket tartalmazó konstruktor hívása.
        else if(tfFAr.getText().equals("")){
            FaButor faButor =new FaButor(tfFNev.getText(), Integer.parseInt(tfFSuly.getText()));
            aruhaz.butorHozzaadasa(faButor);
            String data[]={String.valueOf(jTableButorok.getRowCount()+1),tfFNev.getText(),String.valueOf(faButor.getErtek()),tfFSuly.getText(),"N/A"};
                 
            DefaultTableModel tblModel = (DefaultTableModel)jTableButorok.getModel();
            tblModel.addRow(data);
            JOptionPane.showMessageDialog(this,"Bútor sikeresen hozzáadva!");
            //Adatok bevitelére szolgáló JTextField-ek szövegének visszaállítása  
            tfFNev.setText("");
            tfFSuly.setText("");
        }
        //Ha az érték is megadásra kerül,akkor az ennek megfelelő konstruktor meghívása
        else{
            aruhaz.butorHozzaadasa(new FaButor(tfFNev.getText(),Double.parseDouble(tfFAr.getText()), Integer.parseInt(tfFSuly.getText())));
            String data[]={String.valueOf(jTableButorok.getRowCount()+1),tfFNev.getText(),tfFAr.getText(),tfFSuly.getText(),"N/A"};
        
            DefaultTableModel tblModel = (DefaultTableModel)jTableButorok.getModel();
            tblModel.addRow(data);
            JOptionPane.showMessageDialog(this,"Bútor sikeresen hozzáadva!");
            //Adatok bevitelére szolgáó JTextField-ek szövegének visszaállítása 
            tfFNev.setText("");
            tfFAr.setText("");
            tfFSuly.setText("");
        }
    }//GEN-LAST:event_btFHozzaadasActionPerformed
    
    //Kárpitozott bútor hozzáadása
    private void btKHozzaadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKHozzaadasActionPerformed
        //Kötelező adatok megadásának ellenőrzése
        if(tfKNev.getText().equals("")||tfKAnyag.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Hiányzó adat!","Error",JOptionPane.ERROR_MESSAGE);          
        }
        //Ha a bútor értéke nem került megadásra, akkor a default értéket tartalmazó konstruktor hívása.
        else if(tfKAr.getText().equals("")){
            KarpitozottButor karpitozottButor =new KarpitozottButor(tfKNev.getText(),tfKAnyag.getText());
            aruhaz.butorHozzaadasa(karpitozottButor);
            String data[]={String.valueOf(jTableButorok.getRowCount()+1),tfKNev.getText(),String.valueOf(karpitozottButor.getErtek()),"N/A",tfKAnyag.getText()};
        
            DefaultTableModel tblModel = (DefaultTableModel)jTableButorok.getModel();
            tblModel.addRow(data);
            JOptionPane.showMessageDialog(this,"Bútor sikeresen hozzáadva!");
            //Adatok bevitelére szolgáó JTextField-ek szövegének visszaállítása 
            tfKNev.setText("");
            tfKAnyag.setText("");
        }
        //Ha az érték is megadásra kerül,akkor az ennek megfelelő konstruktor meghívása
        else{
            aruhaz.butorHozzaadasa(new KarpitozottButor(tfKNev.getText(),Double.parseDouble(tfKAr.getText()),tfKAnyag.getText()));
            String data[]={String.valueOf(jTableButorok.getRowCount()+1),tfKNev.getText(),tfKAr.getText(),"N/A",tfKAnyag.getText()};
        
            DefaultTableModel tblModel = (DefaultTableModel)jTableButorok.getModel();
            tblModel.addRow(data);
            JOptionPane.showMessageDialog(this,"Bútor sikeresen hozzáadva!");
            //Adatok bevitelére szolgáó JTextField-ek szövegének visszaállítása 
            tfKNev.setText("");
            tfKAr.setText("");
            tfKAnyag.setText("");
        }
    
    }//GEN-LAST:event_btKHozzaadasActionPerformed

    //Bútorok kiíratása bináris állományba.
    private void btExportalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportalasActionPerformed
        try{
            aruhaz.exportButorok();
            JOptionPane.showMessageDialog(this,"Raktárkészlet sikeresen exportálva.");
        }
        catch(FileNotFoundException f){
            JOptionPane.showMessageDialog(this,"Fájl nem található","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(this,"I/O hiba","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btExportalasActionPerformed
    
    //Bútorok felújítása esetén azok értéke 15%-kal csökken
    private void btFelujitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFelujitasActionPerformed
        //Bútor kiválasztása sorszám alapján
        String sorszam =JOptionPane.showInputDialog(this, "Kérlek add meg a bútor sorszámát:");
        ArrayList<Butor> butorok = aruhaz.getButorok();
        //Amennyiben a bútor sorszámának megadása nem történt meg,a felhasználó figyelmeztetése.
        if(sorszam==null){
            JOptionPane.showMessageDialog(this, "Nem választottál ki bútort!"); 
        }
        //Kiválasztott bútor sorszámának ellenőrzése
        else{
            if(Integer.parseInt(sorszam)<=(butorok.size())&& Integer.parseInt(sorszam)>0){
                butorok.get(Integer.parseInt(sorszam)-1).felujit();
                tablazatbaIr(butorok);
            }
            //Érvénytelen sorszám esetén hibaüzenet megjelenítése
            else{
                JOptionPane.showMessageDialog(this, "Érvénytelen sorszám!","Error",JOptionPane.ERROR_MESSAGE);       
            }
        }
    }//GEN-LAST:event_btFelujitasActionPerformed
    
    //Bútor másolása
    private void btMasolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMasolasActionPerformed
        //Bútor kiválasztása sorszám alapján
        String sorszam =JOptionPane.showInputDialog(this, "Kérlek add meg a bútor sorszámát:");
        ArrayList<Butor> butorok = aruhaz.getButorok();
        //Amennyiben a bútor sorszámának megadása nem történt meg,a felhasználó figyelmeztetése.
        if(sorszam==null){
            JOptionPane.showMessageDialog(this, "Nem választottál ki bútort!"); 
        }
        //Kiválasztott bútor sorszámának ellenőrzése
        else{
            if(Integer.parseInt(sorszam)<=(butorok.size())&& Integer.parseInt(sorszam)>0){
                try{
                    aruhaz.masolas(Integer.parseInt(sorszam)-1);
                    tablazatbaIr(aruhaz.getButorok());
                }
                catch(CloneNotSupportedException c){
                    JOptionPane.showInputDialog(this, "Bútor nem másolható!","Error",JOptionPane.ERROR_MESSAGE); 
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Érvénytelen sorszám!","Error",JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btMasolasActionPerformed
       
    //Bútor anyagának módosítása
    private void btModositasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModositasActionPerformed
        //Bútor kiválasztása sorszám alapján
        String sorszam =JOptionPane.showInputDialog(this, "Kérlek add meg a bútor sorszámát:");
        ArrayList<Butor> butorok = aruhaz.getButorok();
        //Amennyiben a bútor sorszámának megadása nem történt meg,a felhasználó figyelmeztetése.
        if(sorszam==null){
            JOptionPane.showMessageDialog(this, "Nem választottál ki bútort!"); 
        }
        //Kiválasztott bútor sorszámának ellenőrzése
        else{
            if(Integer.parseInt(sorszam)<=(butorok.size())&& Integer.parseInt(sorszam)>0){
                //Csak a kápitozott bútor sorszáma valid sorszám
                if(butorok.get(Integer.parseInt(sorszam)-1) instanceof KarpitozottButor f){        
                   String anyag = JOptionPane.showInputDialog(this, "Milyen anyagra szeretnéd megváltoztatni a bútor kárpitját?");
                   f =(KarpitozottButor)butorok.get(Integer.parseInt(sorszam)-1);
                   f.setAnyag(anyag);
                   tablazatbaIr(butorok);
                }
                //Nem valid sorszám esetén hibaüzenet megjelenítése
                else{
                   JOptionPane.showMessageDialog(this, "A kiválasztott bútor nem kárpitozott bútor!","Error",JOptionPane.ERROR_MESSAGE); 
                }
            }
            //Érvénytelen sorszám esetén hibaüzenet megjelenítése
            else{
                JOptionPane.showMessageDialog(this, "Érvénytelen sorszám!","Error",JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btModositasActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExportalas;
    private javax.swing.JButton btFHozzaadas;
    private javax.swing.JButton btFelujitas;
    private javax.swing.JButton btKHozzaadas;
    private javax.swing.JButton btListazas;
    private javax.swing.JButton btMasolas;
    private javax.swing.JButton btModositas;
    private javax.swing.JButton btRendezes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableButorok;
    private javax.swing.JLabel lAruhazFileNev;
    private javax.swing.JLabel lAruhazNev;
    private javax.swing.JTextField tfFAr;
    private javax.swing.JTextField tfFNev;
    private javax.swing.JTextField tfFSuly;
    private javax.swing.JTextField tfKAnyag;
    private javax.swing.JTextField tfKAr;
    private javax.swing.JTextField tfKNev;
    // End of variables declaration//GEN-END:variables
}
